# Configuration for Streamlit Page Categories

# The 'match' setting can be 'all' (all rules must be true) or 'any' (any rule can be true).
# Example:
# categories:
#   "Peaks Processing":
#     match: all
#     rules:
#       - type: startswith
#         value: "private_"
#       - type: contains
#         value: "peak"
  
#   "Analytics":
#     match: any
#     rules:
#       - type: contains
#         value: "analysis"
#       - type: endswith
#         value: "_analytics.py"

# Add more categories here as needed